# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Degreeless.marketing
email: lukas.murdock@gmail.com
description: You don’t need a degree to make change happen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://degreeless.marketing" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Lukasauras_Rex
github_username:  

# Build settings

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author: Lukas Murdock
logo: "/assets/images/logo.png"
image:
  path: /assets/images/weblogo.png
  height: 628
  width: 1200
social:
  name: Lukas Murdock
  links:
    - https://www.linkedin.com/in/lukas-murdock/
    - https://twitter.com/Lukasauras_Rex


include:
  - _headers

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      permalink: /ideas/:title
      author: lukasmurdock
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "books"
    values:
      image: "book.svg"
      layout: book
      permalink: /books/:slug
  -
    scope:
      path: ""
    values:
      image: /assets/images/weblogo.png
  -
    scope:
      path: "_categories" # an empty string here means all files in the project
      type: "categories"
    values:
      layout: post
      permalink: /ideas/:title
      

# permalink: /:categories/:title

collections:
  books:
    output: true
  posts:
    output: true
    permalink: /ideas/:title
    layout: post
  categories:
    output: true
    permalink: /ideas/:title

feed:
  collections:
    posts:
      path: "/posts.xml"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
